[package]
name = "lilac"
version = "0.1.0"
edition = "2021"
description = "Widget library and tweaks for the druid UI toolkit"
license = "MIT"

[dependencies]
druid = "0.8.3"
piet-common = "0.3"
tracing = "0.1.22"