[package]
name = "lilac"
version = "0.1.0"
edition = "2021"
description = "An immediate mode GUI framework."
license = "MIT"

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["image"]