[package]
name = "lilac"
version = "0.1.0"
edition = "2021"
description = "Widget library and tweaks for the druid UI toolkit"
license = "MIT"

[dependencies]
clap = {version = "4.4.17", features = ["derive"]}